from agent.model_gateway.base import ModelGateway
from agent.model_gateway.factory import ModelGatewayConfig
from agent.model_gateway.schemas import ChatMessageRole
from agent.model_gateway.schemas import ChatRequest
from agent.model_gateway.schemas import ChatResponse


class MockChatProvider(ModelGateway):
    def __init__(self, config: ModelGatewayConfig | None = None) -> None:
        self.config = config or ModelGatewayConfig()

    def generate(self, request: ChatRequest) -> ChatResponse:
        prompt = self._last_user_message(request)
        content = self._build_content(prompt, request)
        return ChatResponse(
            content=content,
            model=request.model or self.config.model_name,
            provider="mock",
            usage={
                "prompt_tokens": self._estimate_tokens(
                    " ".join(message.content for message in request.messages)
                ),
                "completion_tokens": self._estimate_tokens(content),
                "total_tokens": self._estimate_tokens(
                    " ".join(message.content for message in request.messages) + content
                ),
            },
            raw_metadata={
                "mock": True,
                "message_count": len(request.messages),
                "last_user_chars": len(prompt),
                "temperature": request.temperature,
            },
        )

    @staticmethod
    def _last_user_message(request: ChatRequest) -> str:
        for message in reversed(request.messages):
            if message.role == ChatMessageRole.USER:
                return message.content.strip()
        return request.messages[-1].content.strip()

    def _build_content(self, prompt: str, request: ChatRequest) -> str:
        topic = prompt or "未提供主题"
        lines = [
            "## Mock Chat Response",
            "",
            "This response was generated by the local mock chat provider.",
            "",
            f"- Provider: mock",
            f"- Model: {request.model or self.config.model_name}",
            f"- Input summary: {self._excerpt(topic)}",
            "",
            "Use this response only for local smoke tests and no-key demos.",
        ]
        return self._apply_max_tokens("\n".join(lines), request.max_tokens)

    @staticmethod
    def _excerpt(text: str, max_chars: int = 240) -> str:
        normalized = " ".join(text.split())
        if len(normalized) <= max_chars:
            return normalized
        return f"{normalized[:max_chars]}[truncated]"

    @staticmethod
    def _estimate_tokens(text: str) -> int:
        if not text:
            return 0
        return max(1, len(text) // 4)

    @staticmethod
    def _apply_max_tokens(content: str, max_tokens: int | None) -> str:
        if max_tokens is None:
            return content
        max_chars = max_tokens * 4
        if len(content) <= max_chars:
            return content
        return f"{content[:max_chars]}[truncated]"
