builtin_models:
  - id: builtin-chat-default
    type: KnowledgeQA
    source: remote
    is_default: true
    name: ${CHAT_MODEL_NAME}
    parameters:
      base_url: ${CHAT_MODEL_BASE_URL}
      api_key: ${CHAT_MODEL_API_KEY}
      provider: ${CHAT_MODEL_PROVIDER}

  - id: builtin-embedding-default
    type: Embedding
    source: remote
    is_default: true
    name: ${EMBEDDING_MODEL_NAME}
    parameters:
      base_url: ${EMBEDDING_BASE_URL}
      api_key: ${EMBEDDING_API_KEY}
      provider: ${EMBEDDING_PROVIDER}
      embedding_parameters:
        dimension: 1024
        truncate_prompt_tokens: 0

  - id: builtin-rerank-default
    type: Rerank
    source: remote
    is_default: true
    name: ${RERANK_MODEL_NAME}
    parameters:
      base_url: ${RERANK_BASE_URL}
      api_key: ${RERANK_API_KEY}
      provider: ${RERANK_PROVIDER}
